codeforIATI/codelists

static/.vuepress/locales.json
static/ExchangeRates/README.md
static/fr/ExchangeRates/README.md

I've only done this in English so far -- I think this should be replaced once we have a nicer front end for the exchange rates scraper.

Addition exchangerates

---

.travis.yml
src/gen.py

Fixes #8. Output of `/api/index.json` looks like this:
```
{
"languages": {
"en": {
"codelists": {
"AidType": "https://codelists.codeforiati.org/api/json/en/AidType.json",
"AidType-category": "https://codelists.codeforiati.org/api/json/en/AidType-category.json",
"CRSChannelCode": "https://codelists.codeforiati.org/api/json/en/CRSChannelCode.json",
"CollaborationType": "https://codelists.codeforiati.org/api/json/en/CollaborationType.json",
"Country": "https://codelists.codeforiati.org/api/json/en/Country.json",
"Currency": "https://codelists.codeforiati.org/api/json/en/Currency.json",
"EarmarkingCategory": "https://codelists.codeforiati.org/api/json/en/EarmarkingCategory.json",
"FileFormat": "https://codelists.codeforiati.org/api/json/en/FileFormat.json",
"FinanceType": …
```

Generate codelists routes for API root

---

src/gen.py

Output looks like this:
```json
{
"languages": {
"en": {
"xml": {
"AidType": "/api/xml/AidType.xml",
"AidType-category": "/api/xml/AidType-category.xml",
"CRSChannelCode": "/api/xml/CRSChannelCode.xml",
"CollaborationType": "/api/xml/CollaborationType.xml",
"Country": "/api/xml/Country.xml",
"Currency": "/api/xml/Currency.xml",
"EarmarkingCategory": "/api/xml/EarmarkingCategory.xml",
"FileFormat": "/api/xml/FileFormat.xml",
"FinanceType": "/api/xml/FinanceType.xml",
"FinanceType-category": "/api/xml/FinanceType-category.xml",
"FlowType": "/api/xml/FlowType.xml",
"Language": "/api/xml/Language.xml",
"LocationType": "/api/xml/LocationType.xml",
"LocationType-category": "/api/xml/LocationType-category.xml",
"OrganisationRegistrationAgency": "/api/xml/OrganisationRegistrationAgency.xml", …
```

Make data available in multiple formats

---

requirements.txt
src/gen.py
src/gen.sh
src/v2tov1.py
src/xlsx.py
static/.vuepress/components/CodelistPage.vue

Generate Excel files

---

static/.vuepress/config.js

Fixes #28.
Alignment doesn’t look quite right here…?

Add API to navbar

---

package.json
static/.vuepress/components/CodelistPage.vue
static/.vuepress/enhanceApp.js
yarn.lock

Fixes #5.
NB the inline style here is to compensate for the sticky nav. I don’t know if this is better off in a stylesheet? But it looks like we don’t have one yet, and I wasn’t sure how to add one!

Add links for individual codes

---

static/.vuepress/config.js

Another go at getting #28 working.

Use an absolute link instead :(

---

src/gen.py

Ignore self-closing narratives

---

static/.vuepress/config.js

Remove previous and next links

---

static/.vuepress/components/CodelistPage.vue
static/.vuepress/locales.json

Translate codelists withdrawn status; do it in a way that is somewhat generalisable in future. Fixes #15 :)

Translate codelist withdrawn status

---

.gitignore
src/gen.sh

…from codeforIATI/IATI-Codelists-Extra
Addresses #3.

Include extra codelists

---

src/gen.py
static/.vuepress/components/CodelistPage.vue
static/.vuepress/locales.json

On the Sector page, information according to the [IATI budget alignment guidance](http://reference.iatistandard.org/203/activity-standard/overview/country-budget-alignment/) should be shown. Codes that are not recommended according to the guidance are marked in red.

Show budget alignment guidance

---

requirements.txt
src/gen.py
static/.vuepress/components/CodelistPage.vue
static/.vuepress/locales.json

Add the last updated date for each codelist using the most recent git commit date for each codelist file

Add last updated date

---

src/gen.py
src/gen.sh

This is required in order to make the UNM49 codelist visible

Show additional columns according to XML file

---

src/gen.sh
static/.vuepress/components/CodelistPage.vue
static/.vuepress/locales.json

GLIDENumber is now available from [codeforIATI/Unofficial-Codelists](https://github.com/codeforIATI/Unofficial-Codelists)

Display GLIDENumber

---

.gitignore
src/gen.py
src/gen.sh

Include all non-embedded and embedded codelists

---

static/.vuepress/locales.json

I missed a couple of translations

Add missing translations for GLIDE code

---

static/.vuepress/components/CodelistPage.vue

Make download button full width of container and only show blue info box if it contains something

Minor stylistic tweaks

---

static/.vuepress/components/CodelistPage.vue

Allow a user to filter a codelist. Make some tweaks to the styling of the pagination for consistency

Add filter codelist

---

static/.vuepress/locales.json

No idea if this is right!
Fixes #53.

Add missing public-database translations

---

static/.vuepress/components/CodelistPage.vue

Prevent text flooding (usually of long URLs)

---

static/.vuepress/locales.json

Relates to https://codelists.codeforiati.org/HumanitarianPlan/
Not sure about the French translations! Could you check, @markbrough?

Humanitarian plan locales

---

src/gen.py

Generate PT codelists in API where available

Add Portuguese codelists

---

static/.vuepress/components/CodelistPage.vue

Split categories when there are multiple (semicolon-separated)

Fix multiple categories

---

requirements.txt

Upgrade all Python dependencies

Upgrade Python dependencies
